services:
  - type: web
    name: masah
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/database.sqlite
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: database-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1 